name: Feature request
description: Make a request for a new feature in the Danfoss Ally integration
title: "[FR]: "
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        This form is only for requesting new features to the integration.

        Remember to add a descriptive title after the predefined text.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the feature you wish to make a request for
      description: >-
        Provide a clear and concise description of what you wish for.
        The more precise and detailed the more likely it is to be accepted and made.
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: >-
        Have you considered any alternatives (ie. other existing integrations that can handle this)
  - type: textarea
    attributes:
      label: Additional context
      description: >-
        Add any other context or screenshots about the feature request here.
