blueprint:
  name: Danfoss Ally™ External Temperature
  description: Link one or more external temperature sensors to one or more Danfoss Ally thermostats
  domain: automation
  author: Thomas Barnekov
  input:
    temperature_sensors:
      name: Temperature sensor
      description: "This sensor will be used to measure the temperature"
      selector:
        entity:
          multiple: true
          filter:
            - domain: sensor
              device_class: temperature
    target_thermostats:
      name: Ally thermostat
      description: "The selected thermostat(s) will be updated using the external temperature measured by the sensor(s) selected above"
      selector:
        target:
          entity:
            - integration: danfoss_ally
              domain: climate
          device:
            - integration: danfoss_ally
              model: "Danfoss Ally™ Radiator Thermostat"

variables:
  temperature_entities: !input temperature_sensors

trigger:
  - platform: state
    entity_id: !input temperature_sensors
  - platform: time_pattern
    minutes: /30

action:
  - alias: Set external temperature
    service: danfoss_ally.set_external_temperature
    data:
      temperature: >
        {% set sensors = expand(temperature_entities) | map(attribute='state') | map('float', none) | reject('eq', none) | list %}
        {{ ((sensors | sum) / (sensors | count)) | round(2) }}
    target: !input target_thermostats

      
