name: Lint

on:
  pull_request:
  push:
    tags-ignore:
      - "*"

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Python 3.14
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run ruff check
        run: ruff check .
      - name: Run ruff format check
        run: ruff format --check .
