name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: "Set manifest version number"
        run: |
          python3 ${{ github.workspace }}/.github/scripts/update_hacs_manifest.py --version ${{ steps.version.outputs.version }}
      - name: Create zip
        run: |
          cd custom_components/danfoss_ally
          zip danfoss_ally.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/danfoss_ally/danfoss_ally.zip
          asset_name: danfoss_ally.zip
          tag: ${{ github.ref }}
          overwrite: true